// Video script content
// This file is auto-generated by /new-reel command or can be manually edited

export interface Segment {
  text: string;
  duration: number;
  visual: string;
}

export interface VideoScript {
  hook: Segment;
  body: Segment[];
  cta: Segment;
  metadata: {
    total_duration: number;
    hook_pattern: string;
    hashtags: string[];
  };
}

export const CONTENT: VideoScript = {
  hook: {
    text: "Todo criador de conteúdo que usa IA pra fazer vídeos mais rápido tá na verdade perdendo mais tempo. E eu vou provar isso agora.",
    duration: 5,
    visual: "Close-up direto pra câmera, expressão séria, texto overlay: 'VOCÊ TÁ USANDO IA ERRADO'",
  },
  body: [
    {
      text: "A galera acha que automação com IA é só apertar um botão e pronto. Aí passa 3 horas tentando fazer o ChatGPT gerar um roteiro decente, mais 2 horas editando porque a IA não entendeu o seu tom de voz.",
      duration: 12,
      visual: "B-roll: tela de computador com múltiplas abas do ChatGPT abertas, pessoa frustrada olhando pro relógio",
    },
    {
      text: "Resultado? 5 horas pra fazer um vídeo que você faria em 30 minutos sozinho. Mas ninguém fala disso porque todo mundo quer vender curso de IA.",
      duration: 8,
      visual: "Split screen: relógio correndo rápido de um lado, criador cansado do outro",
    },
    {
      text: "A verdade que ninguém conta: IA só acelera quando você tem SISTEMA. Não é a ferramenta, é o processo. Você precisa de prompts salvos, templates testados, workflow definido.",
      duration: 12,
      visual: "Mostrar notion/doc com templates organizados, prompts salvos, checklist de produção",
    },
    {
      text: "Eu testo IA de conteúdo todo dia. Sabe o que funciona de verdade? IA pra 3 coisas específicas: ideação em massa, primeiro rascunho de roteiro, e legendas. Só. O resto é você.",
      duration: 13,
      visual: "Motion graphics mostrando os 3 usos específicos, com ícones e exemplos rápidos",
    },
    {
      text: "E mais: se você tá pagando 5 ferramentas diferentes de IA pra criar vídeo, você tá queimando dinheiro. Uma ferramenta bem usada vale mais que dez mal aproveitadas.",
      duration: 10,
      visual: "Animação de notas de dinheiro pegando fogo, depois mostra dashboard com múltiplas subscriptions",
    },
  ],
  cta: {
    text: "Comenta aqui quantas ferramentas de IA você paga e nem usa direito. Vou responder todo mundo.",
    duration: 5,
    visual: "Volta pro close-up, gesto apontando pra baixo (comentários), overlay: 'COMENTA AÍ'",
  },
  metadata: {
    total_duration: 60,
    hook_pattern: "pattern_interrupt",
    hashtags: [
      "#IAParaCriadores",
      "#AutomacaoDeConteudo",
      "#CriacaoDeVideos",
      "#ProdutividadeIA",
      "#ChatGPT",
      "#CreatorEconomy",
      "#DicasDeConteudo",
      "#InteligenciaArtificial",
    ],
  },
};
